### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/css-color-names#1]
- [x] Get rid of alpha channel derp
- [ ] List hex and rgb
- [ ] Consider releasing a color-groups.json based on [Wikipedia](https://en.wikipedia.org/wiki/Web_colors#X11_color_names)

Example:

```
{
  "cornsilk": {
      "hex": "fff8dc",
      "rgb": [
        "255",
        "248",
        "220"
      ]
  }
}
```
